### ISSUE TITLE
indirect_value::swap reference implementation do not work with empty optimization

### ISSUE THREAD

**Issue by viboes** [jbcoe/indirect_value#42]
The line 

https://github.com/jbcoe/indirect_value/blob/master/indirect_value.h#L94

uses a unexisting field c_.

    swap(lhs.c_, rhs.c_);

**Comment by Twon** [comment]
Thanks for opening this issue.  There should be a test for the swap method which should have caught this.  I'll fix this and add a test case for the swap method.

**Comment by Twon** [comment]
Pull request raised to address this issue: https://github.com/jbcoe/indirect_value/pull/44

**Comment by Twon** [comment]
Fix checked in with test cases to verify.
