### ISSUE TITLE
Add a GDB pretty-printer

### ISSUE THREAD

**Issue by jbcoe** [jbcoe/indirect_value#55]
See: https://sourceware.org/gdb/onlinedocs/gdb/Pretty-Printing.html

**Comment by jbcoe** [comment]
See https://github.com/jbcoe/polymorphic_value/issues/91 for implementation guidance.

**Comment by jbcoe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pretty printers for GBD & LLDB](https://trello.com/c/5QH0UQ8W/6-pretty-printers-for-gbd-lldb)

**Comment by jbcoe** [comment]
See https://github.com/jbcoe/polymorphic_value/issues/91 which we can pretty much just adopt.

**Comment by Twon** [comment]
This has now been added in this commit: https://github.com/jbcoe/indirect_value/commit/3fb4e72311213741d37b11f83d0250925f483f6a
