### ISSUE TITLE
Amendments to the paper

### ISSUE THREAD

**Issue by Twon** [jbcoe/indirect_value#62]
Wording comments

- Please make sure that library description elements are ordered canonically (see [structure.specifications] for the canonical order)  
- Please add a comma before "or bad_alloc" to clarify conditions.
- Please replace the term "CopyConstructible", it is not in use on C++20.  
- indirect_value& operator=(const indirect_value& p); "the copy is created by the copier in p" Please align with standard wording.

**Comment by jbcoe** [comment]
We plan to consolidate polymorphic_value and indirect_value papers so this is is no longer relevant.
