### ISSUE TITLE
Move constructor and completeness of T

### ISSUE THREAD

**Issue by Ukilele** [jbcoe/indirect_value#73]
[3.4. Completeness of T](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1950r1.html#completeness-of-t) says that in the move constructor of `indirect_value`, the type `T` may be incomplete. This matches the specification of e.g. `std::unique_ptr`. But in the current implementation of `indirect_value`, the type `T` has to be complete in the move constructor (if using a deleter which needs `T` to be complete when being invoked). This is due to https://eel.is/c++draft/class.base.init#12. Example: https://godbolt.org/z/s11K14KxP
I see two options:
1. Change the wording of §3.4. to say that the move constructor of `indirect_value` needs `T` to be complete.
2. Change the implementation of `indirect_value` to not store a `unique_ptr<T, D>` but storing a `T*` directly and manually implement the unique_ptr's functionality.

What is your opinion?

**Comment by jbcoe** [comment]
I think option 2 is good. We want indirect_value to be a better unique_ptr so don’t want to be hampered where it can be avoided.

**Comment by jbcoe** [comment]
Thanks for your patience, I’m still thinking about this.

I don’t think that we should be calling the move constructor of the owned object at any point.

Making non-moveable types movable through indirection is a good use-case for indirect_value.

**Comment by Ukilele** [comment]
No problem. There is no need to rush and it's better to carefully think about this.

Are we having a communication issue here? The move constructor of the owned object is never called. It is the move constructor of `indirect_value` which gets called. And before calling that move constructor, the compiler has to create an overload set of the constructors for `indirect_value` to find out, that the move constructor is the one, we want to call when writing: `indirect_value<Incomplete> b(std::move(a));`. But when building this overload set, the requires-clause `ISOCPP_P1950_REQUIRES(std::is_copy_constructible_v<T>)` needs to get evaluated. And this is the point where we get a compilation error, when `T` is an incomplete type.

**Comment by jbcoe** [comment]
Communication issue seems to be only one way - you understood me perfectly 😆 

Option 2 sounds good - are you happy to put together a PR?

**Comment by Ukilele** [comment]
Glad that we resolved it that quickly 😄
I will make a PR soon.
